<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Module;

class ModulesSeeder extends Seeder
{
    public function run(): void
    {
        $modules = [
            [
                'slug'        => 'accounts',
                'name'        => 'Accounts',
                'label'       => 'Accounts',
                'icon'        => 'fa-building',
                'color'       => '#0d6efd',
                'path'        => '/accounts',
                'sort_order'  => 1,
                'is_active'   => true,
                'description' => 'Company records and organizations.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\Account',
                'table_name'  => 'accounts',
            ],

            [
                'slug'        => 'contacts',
                'name'        => 'Contacts',
                'label'       => 'Contacts',
                'icon'        => 'fa-user',
                'color'       => '#6610f2',
                'path'        => '/contacts',
                'sort_order'  => 2,
                'is_active'   => true,
                'description' => 'People assigned to accounts or leads.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\Contact',
                'table_name'  => 'contacts',
            ],

            [
                'slug'        => 'leads',
                'name'        => 'Leads',
                'label'       => 'Leads',
                'icon'        => 'fa-user-plus',
                'color'       => '#20c997',
                'path'        => '/leads',
                'sort_order'  => 3,
                'is_active'   => true,
                'description' => 'Prospective customers with interest.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\Lead',
                'table_name'  => 'leads',
            ],

            [
                'slug'        => 'invoices',
                'name'        => 'Invoices',
                'label'       => 'Invoices',
                'icon'        => 'fa-file-invoice',
                'color'       => '#fd7e14',
                'path'        => '/invoices',
                'sort_order'  => 4,
                'is_active'   => true,
                'description' => 'Customer invoices and billing.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\Invoice',
                'table_name'  => 'invoices',
            ],

            [
                'slug'        => 'quotes',
                'name'        => 'Quotes',
                'label'       => 'Quotes',
                'icon'        => 'fa-file-lines',
                'color'       => '#ffc107',
                'path'        => '/quotes',
                'sort_order'  => 5,
                'is_active'   => true,
                'description' => 'Sales proposals and quotes.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\Quote',
                'table_name'  => 'quotes',
            ],

            [
                'slug'        => 'cases',
                'name'        => 'Cases',
                'label'       => 'Cases',
                'icon'        => 'fa-life-ring',
                'color'       => '#dc3545',
                'path'        => '/cases',
                'sort_order'  => 6,
                'is_active'   => true,
                'description' => 'Support requests, bugs, tickets.',
                'can_view'    => true,
                'can_create'  => true,
                'can_edit'    => true,
                'can_delete'  => true,
                'model_class' => 'App\\Models\\CaseModel',
                'table_name'  => 'cases',
            ],

            [
                'slug'        => 'emails',
                'name'        => 'Emails',
                'label'       => 'Emails',
                'icon'        => 'fa-envelope',
                'color'       => '#0dcaf0',
                'path'        => '/emails',
                'sort_order'  => 7,
                'is_active'   => true,
                'description' => 'Email communication module.',
                'can_view'    => true,
                'can_create'  => false,
                'can_edit'    => false,
                'can_delete'  => false,
                'model_class' => null,
                'table_name'  => null,
            ],
        ];
        $leads = [
            [
                'id' => '550e8400-e29b-41d4-a716-446655440000',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'name' => 'John Smith',
                'email' => 'john.smith@example.com',
                'phone' => '+1-555-0101',
                'company' => 'Tech Solutions Inc',
                'street' => '123 Main Street',
                'city' => 'New York',
                'zip' => '10001',
                'description' => 'Interested in enterprise software solutions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440001',
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'name' => 'Sarah Johnson',
                'email' => 'sarah.j@techcorp.com',
                'phone' => '+1-555-0102',
                'company' => 'Digital Innovations LLC',
                'street' => '456 Oak Avenue',
                'city' => 'San Francisco',
                'zip' => '94102',
                'description' => 'Looking for CRM integration services.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440002',
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'name' => 'Michael Brown',
                'email' => 'michael.b@example.com',
                'phone' => '+1-555-0103',
                'company' => 'Global Enterprises',
                'street' => '789 Pine Street',
                'city' => 'Chicago',
                'zip' => '60601',
                'description' => 'Enterprise client with multiple locations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440003',
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'name' => 'Emily Davis',
                'email' => 'emily.davis@startup.io',
                'phone' => '+1-555-0104',
                'company' => 'StartUp Innovations',
                'street' => '321 Elm Road',
                'city' => 'Austin',
                'zip' => '73301',
                'description' => 'Tech startup seeking growth solutions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440004',
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'name' => 'David Wilson',
                'email' => 'dwilson@corp.com',
                'phone' => '+1-555-0105',
                'company' => 'Wilson & Sons Manufacturing',
                'street' => '654 Industrial Way',
                'city' => 'Detroit',
                'zip' => '48201',
                'description' => 'Manufacturing company automation needs.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440005',
                'first_name' => 'Jennifer',
                'last_name' => 'Martinez',
                'name' => 'Jennifer Martinez',
                'email' => 'j.martinez@retailgroup.com',
                'phone' => '+1-555-0106',
                'company' => 'Retail Group International',
                'street' => '987 Market Street',
                'city' => 'Miami',
                'zip' => '33101',
                'description' => 'Retail chain expansion project.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440006',
                'first_name' => 'Robert',
                'last_name' => 'Taylor',
                'name' => 'Robert Taylor',
                'email' => 'robert.t@finance.com',
                'phone' => '+1-555-0107',
                'company' => 'Secure Finance Partners',
                'street' => '147 Wall Street',
                'city' => 'New York',
                'zip' => '10005',
                'description' => 'Financial services compliance software.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440007',
                'first_name' => 'Lisa',
                'last_name' => 'Anderson',
                'name' => 'Lisa Anderson',
                'email' => 'lisa.anderson@health.org',
                'phone' => '+1-555-0108',
                'company' => 'Healthcare Solutions',
                'street' => '258 Medical Drive',
                'city' => 'Boston',
                'zip' => '02108',
                'description' => 'Medical practice management system.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440008',
                'first_name' => 'James',
                'last_name' => 'Thomas',
                'name' => 'James Thomas',
                'email' => 'james.thomas@builders.com',
                'phone' => '+1-555-0109',
                'company' => 'Thomas Construction Co',
                'street' => '369 Builder Avenue',
                'city' => 'Phoenix',
                'zip' => '85001',
                'description' => 'Construction project management needs.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440009',
                'first_name' => 'Amanda',
                'last_name' => 'White',
                'name' => 'Amanda White',
                'email' => 'amanda.white@edu.edu',
                'phone' => '+1-555-0110',
                'company' => 'University Systems',
                'street' => '741 Campus Lane',
                'city' => 'Seattle',
                'zip' => '98101',
                'description' => 'Educational institution software upgrade.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440010',
                'first_name' => 'Christopher',
                'last_name' => 'Lee',
                'name' => 'Christopher Lee',
                'email' => 'chris.lee@techguru.com',
                'phone' => '+1-555-0111',
                'company' => 'Tech Guru Solutions',
                'street' => '852 Silicon Road',
                'city' => 'San Jose',
                'zip' => '95101',
                'description' => 'IT consulting services inquiry.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440011',
                'first_name' => 'Michelle',
                'last_name' => 'Garcia',
                'name' => 'Michelle Garcia',
                'email' => 'm.garcia@logistics.com',
                'phone' => '+1-555-0112',
                'company' => 'Global Logistics Inc',
                'street' => '963 Shipping Way',
                'city' => 'Los Angeles',
                'zip' => '90001',
                'description' => 'Supply chain management software.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440012',
                'first_name' => 'Daniel',
                'last_name' => 'Rodriguez',
                'name' => 'Daniel Rodriguez',
                'email' => 'dan.rod@creative.com',
                'phone' => '+1-555-0113',
                'company' => 'Creative Agency Partners',
                'street' => '159 Design Street',
                'city' => 'Portland',
                'zip' => '97201',
                'description' => 'Marketing agency project management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440013',
                'first_name' => 'Jessica',
                'last_name' => 'Harris',
                'name' => 'Jessica Harris',
                'email' => 'jessica.h@realestate.com',
                'phone' => '+1-555-0114',
                'company' => 'Prime Real Estate Group',
                'street' => '753 Property Avenue',
                'city' => 'Denver',
                'zip' => '80201',
                'description' => 'Real estate CRM system requirements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440014',
                'first_name' => 'Kevin',
                'last_name' => 'Clark',
                'name' => 'Kevin Clark',
                'email' => 'kevin.clark@energy.com',
                'phone' => '+1-555-0115',
                'company' => 'Green Energy Solutions',
                'street' => '456 Solar Lane',
                'city' => 'Houston',
                'zip' => '77001',
                'description' => 'Renewable energy company expansion.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440015',
                'first_name' => 'Nicole',
                'last_name' => 'Lewis',
                'name' => 'Nicole Lewis',
                'email' => 'n.lewis@consulting.com',
                'phone' => '+1-555-0116',
                'company' => 'Strategic Consulting Group',
                'street' => '258 Advisor Road',
                'city' => 'Atlanta',
                'zip' => '30301',
                'description' => 'Business consulting firm software needs.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440016',
                'first_name' => 'Matthew',
                'last_name' => 'Walker',
                'name' => 'Matthew Walker',
                'email' => 'matt.walker@auto.com',
                'phone' => '+1-555-0117',
                'company' => 'Auto Parts Distributors',
                'street' => '147 Garage Street',
                'city' => 'Dallas',
                'zip' => '75201',
                'description' => 'Automotive parts inventory system.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440017',
                'first_name' => 'Stephanie',
                'last_name' => 'Hall',
                'name' => 'Stephanie Hall',
                'email' => 'stephanie.hall@foodgroup.com',
                'phone' => '+1-555-0118',
                'company' => 'Fresh Food Distributors',
                'street' => '369 Farm Road',
                'city' => 'Minneapolis',
                'zip' => '55401',
                'description' => 'Food distribution logistics software.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440018',
                'first_name' => 'Andrew',
                'last_name' => 'Allen',
                'name' => 'Andrew Allen',
                'email' => 'andrew.allen@insurance.com',
                'phone' => '+1-555-0119',
                'company' => 'Secure Insurance Partners',
                'street' => '852 Policy Lane',
                'city' => 'Philadelphia',
                'zip' => '19101',
                'description' => 'Insurance agency management system.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '550e8400-e29b-41d4-a716-446655440019',
                'first_name' => 'Rachel',
                'last_name' => 'Young',
                'name' => 'Rachel Young',
                'email' => 'rachel.young@pharma.com',
                'phone' => '+1-555-0120',
                'company' => 'Pharma Research Labs',
                'street' => '741 Science Park',
                'city' => 'San Diego',
                'zip' => '92101',
                'description' => 'Pharmaceutical research data management.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($modules as $module) {
            Module::create($module);   // UUID auto-generated here
        }
        DB::table('leads')->insert($leads);
    }
}
