<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modules')->delete();
        
        \DB::table('modules')->insert(array (
            0 => 
            array (
                'id' => '019aa1a5-738b-707e-bf52-b71c30b565f2',
                'name' => 'Accounts',
                'slug' => 'accounts',
                'label' => 'modules.accounts.label',
                'icon' => 'fa-solid fa-jet-fighter',
                'color' => '#0d6efd',
                'path' => '/accounts',
                'sort_order' => 1,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Company records and organizations.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Account',
                'table_name' => 'accounts',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-12-01 13:08:05',
                'is_custom' => 0,
            ),
            1 => 
            array (
                'id' => '019aa1a5-7391-728b-b209-5398a0c7c895',
                'name' => 'Contacts',
                'slug' => 'contacts',
                'label' => 'modules.contacts.label',
                'icon' => 'fa-solid fa-magnifying-glass-arrow-right',
                'color' => '#5e63a4',
                'path' => '/contacts',
                'sort_order' => 2,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'People assigned to accounts or leads.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Contact',
                'table_name' => 'contacts',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-12-04 10:09:58',
                'is_custom' => 0,
            ),
            2 => 
            array (
                'id' => '019aa1a5-7393-73bf-9a57-549ae2311228',
                'name' => 'Leads',
                'slug' => 'leads',
                'label' => 'modules.leads.label',
                'icon' => 'fa-solid fa-user-plus',
                'color' => '#9d8f4d',
                'path' => '/leads',
                'sort_order' => 3,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Prospective customers with interest.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Lead',
                'table_name' => 'leads',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-12-03 16:41:27',
                'is_custom' => 0,
            ),
            3 => 
            array (
                'id' => '019aa1a5-7394-71ff-82e5-ee77dbf247d7',
                'name' => 'Invoices',
                'slug' => 'invoices',
                'label' => 'modules.invoices.label',
                'icon' => 'fa-solid fa-file-invoice',
                'color' => '#fd7e14',
                'path' => '/invoices',
                'sort_order' => 4,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Customer invoices and billing.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Invoice',
                'table_name' => 'invoices',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-11-29 21:59:27',
                'is_custom' => 0,
            ),
            4 => 
            array (
                'id' => '019aa1a5-7396-7101-a5ad-302f72854ab6',
                'name' => 'Quotes',
                'slug' => 'quotes',
                'label' => 'modules.quotes.label',
                'icon' => 'fa-solid fa-file-invoice-dollar',
                'color' => '#ffc107',
                'path' => '/quotes',
                'sort_order' => 5,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Sales proposals and quotes.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Quote',
                'table_name' => 'quotes',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-11-29 21:59:27',
                'is_custom' => 0,
            ),
            5 => 
            array (
                'id' => '019aa1a5-7398-720d-a850-040590cccc3a',
                'name' => 'Cases',
                'slug' => 'cases',
                'label' => 'modules.cases.label',
                'icon' => 'fa-solid fa-life-ring',
                'color' => '#dc3545',
                'path' => '/cases',
                'sort_order' => 6,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Support requests, bugs, tickets.',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\SupportCase',
                'table_name' => 'cases',
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-11-29 21:59:27',
                'is_custom' => 0,
            ),
            6 => 
            array (
                'id' => '019aa1a5-739a-73b8-8594-27982776449c',
                'name' => 'Emails',
                'slug' => 'emails',
                'label' => 'modules.emails.label',
                'icon' => 'fa-solid fa-envelope',
                'color' => '#0dcaf0',
                'path' => '/emails',
                'sort_order' => 7,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => NULL,
                'description' => 'Email communication module.',
                'can_view' => 1,
                'can_create' => 0,
                'can_edit' => 0,
                'can_delete' => 0,
                'model_class' => 'App\\Models\\Modules\\Email',
                'table_name' => NULL,
                'created_at' => '2025-11-20 14:22:46',
                'updated_at' => '2025-12-04 10:12:05',
                'is_custom' => 0,
            ),
            7 => 
            array (
                'id' => '019ac112-6f77-72fa-b00c-51c95b1f57a8',
                'name' => 'Money',
                'slug' => 'money',
                'label' => 'modules.money.label',
                'icon' => 'fa-solid fa-database',
                'color' => '#8080c0',
                'path' => '/money',
                'sort_order' => 8,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => 'App\\Handlers\\Modules\\Custom\\MoneyModuleHandler',
                'description' => '',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Custom\\Money',
                'table_name' => 'money_cstm',
                'created_at' => '2025-11-26 16:50:02',
                'updated_at' => '2025-11-29 21:59:27',
                'is_custom' => 1,
            ),
            8 => 
            array (
                'id' => '0d4fc7e6-7463-4458-ab5a-6357ee4f2a2d',
                'name' => 'Inquiries',
                'slug' => 'inquiries',
                'label' => 'modules.inquiries.label',
                'icon' => 'fa-solid fa-mail-bulk',
                'color' => '#cceb34',
                'path' => '/inquiries',
                'sort_order' => 0,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => 'App\\Handlers\\Modules\\InquiriesModuleHandler',
                'description' => 'Manage messages from the contact form',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\ContactMessage',
                'table_name' => 'contact_messages',
                'created_at' => '2025-11-22 21:47:37',
                'updated_at' => '2025-11-29 21:59:27',
                'is_custom' => 0,
            ),
            9 => 
            array (
                'id' => '5d088917-1940-49cb-8207-ab951ba090e3',
                'name' => 'Settings',
                'slug' => 'settings',
                'label' => 'modules.settings.label',
                'icon' => 'fa-gears',
                'color' => '#7c45ba',
                'path' => '/settings',
                'sort_order' => 0,
                'is_active' => 1,
                'show_in_sidebar' => 1,
                'handler_class' => 'App\\Handlers\\Modules\\SettingsModuleHandler',
                'description' => 'Settings',
                'can_view' => 1,
                'can_create' => 1,
                'can_edit' => 1,
                'can_delete' => 1,
                'model_class' => 'App\\Models\\Modules\\Settings',
                'table_name' => 'settings',
                'created_at' => '2025-11-23 18:44:44',
                'updated_at' => '2025-12-04 10:10:02',
                'is_custom' => 0,
            ),
        ));
        
        
    }
}