<?php
return [
  'YYYY-MM-DD HH:mm'        => 'Y-m-d H:i',
  'DD.MM.YYYY HH:mm'        => 'd.m.Y H:i',
  'DD/MM/YYYY HH:mm'        => 'd/m/Y H:i',
  'MM/DD/YYYY hh:mm A'      => 'm/d/Y h:i A',
  'MMM DD, YYYY HH:mm'      => 'M d, Y H:i',
  'ddd, DD MMM YYYY HH:mm'  => 'D, d M Y H:i',
  'dddd, DD.MM.YYYY HH:mm'  => 'l, d.m.Y H:i',
  'YYYY-MM-DD'              => 'Y-m-d',
  'DD.MM.YYYY'              => 'd.m.Y',
  'DD/MM/YYYY'              => 'd/m/Y',
  'DD.MM.YYYY HH:mm:ss'     => 'd.m.Y H:i:s',
  'DD.MM.YY HH:mm'          => 'd.m.y H:i',
  'DD.MM.YYYY, HH:mm'       => 'd.m.Y, H:i',
  'DD.MM.YYYY - HH:mm'      => 'd.m.Y - H:i',
  'YYYY-MM-DDTHH:mm'        => 'Y-m-d\TH:i',
  'DD.MM.YY'                => 'd.m.y',
  'DD. MM. YYYY'            => 'd. m. Y',
  'ddd, DD.MM.YYYY'         => 'D, d.m.Y',
  'dddd, DD.MM.YYYY'        => 'l, d.m.Y',
  'DD. MMM YYYY'            => 'd. M Y',
  'DD. MMMM YYYY'           => 'd. F Y',
];
