<?php

return [
    'deals_type_list' => [
        [
            'label' => 'dropdowns.deals_type_list.new_business',
            'value' => 'new_business',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.deals_type_list.existing_business',
            'value' => 'existing_business',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.deals_type_list.renewal',
            'value' => 'renewal',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.deals_type_list.upsell',
            'value' => 'upsell',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
    ],
    'orders_status_list' => [
        [
            'label' => 'dropdowns.orders_status_list.draft',
            'value' => 'draft',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.orders_status_list.pending',
            'value' => 'pending',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.orders_status_list.confirmed',
            'value' => 'confirmed',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.orders_status_list.processing',
            'value' => 'processing',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.orders_status_list.completed',
            'value' => 'completed',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.orders_status_list.cancelled',
            'value' => 'cancelled',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'deals_sales_stage_list' => [
        [
            'label' => 'dropdowns.deals_sales_stage_list.prospecting',
            'value' => 'prospecting',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.deals_sales_stage_list.qualification',
            'value' => 'qualification',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.deals_sales_stage_list.proposal',
            'value' => 'proposal',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.deals_sales_stage_list.negotiation',
            'value' => 'negotiation',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.deals_sales_stage_list.closed_won',
            'value' => 'closed_won',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.deals_sales_stage_list.closed_lost',
            'value' => 'closed_lost',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'cases_status_list' => [
        [
            'label' => 'dropdowns.cases_status_list.open',
            'value' => 'open',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.cases_status_list.in_progress',
            'value' => 'in_progress',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.cases_status_list.pending_input',
            'value' => 'pending_input',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.cases_status_list.rejected',
            'value' => 'rejected',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.cases_status_list.closed',
            'value' => 'closed',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
    ],
    'invoices_status_list' => [
        [
            'label' => 'dropdowns.invoices_status_list.draft',
            'value' => 'draft',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.sent',
            'value' => 'sent',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.viewed',
            'value' => 'viewed',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.partial',
            'value' => 'partial',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.paid',
            'value' => 'paid',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.overdue',
            'value' => 'overdue',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.invoices_status_list.void',
            'value' => 'void',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'quotes_status_list' => [
        [
            'label' => 'dropdowns.quotes_status_list.draft',
            'value' => 'draft',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.quotes_status_list.sent',
            'value' => 'sent',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.quotes_status_list.viewed',
            'value' => 'viewed',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.quotes_status_list.accepted',
            'value' => 'accepted',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.quotes_status_list.rejected',
            'value' => 'rejected',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.quotes_status_list.expired',
            'value' => 'expired',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
    ],
    'cases_priority_list' => [
        [
            'label' => 'dropdowns.cases_priority_list.low',
            'value' => 'low',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.cases_priority_list.medium',
            'value' => 'medium',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.cases_priority_list.high',
            'value' => 'high',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.cases_priority_list.urgent',
            'value' => 'urgent',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'tasks_status_list' => [
        [
            'label' => 'dropdowns.tasks_status_list.not_started',
            'value' => 'not_started',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.tasks_status_list.in_progress',
            'value' => 'in_progress',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.tasks_status_list.completed',
            'value' => 'completed',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.tasks_status_list.deferred',
            'value' => 'deferred',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
    ],
    'tasks_priority_list' => [
        [
            'label' => 'dropdowns.tasks_priority_list.low',
            'value' => 'low',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.tasks_priority_list.medium',
            'value' => 'medium',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.tasks_priority_list.high',
            'value' => 'high',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'calls_direction_list' => [
        [
            'label' => 'dropdowns.calls_direction_list.inbound',
            'value' => 'inbound',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.calls_direction_list.outbound',
            'value' => 'outbound',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
    ],
    'calls_status_list' => [
        [
            'label' => 'dropdowns.calls_status_list.planned',
            'value' => 'planned',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.calls_status_list.held',
            'value' => 'held',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.calls_status_list.not_held',
            'value' => 'not_held',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'calls_outcome_list' => [
        [
            'label' => 'dropdowns.calls_outcome_list.connected',
            'value' => 'connected',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.calls_outcome_list.no_answer',
            'value' => 'no_answer',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.calls_outcome_list.voicemail',
            'value' => 'voicemail',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.calls_outcome_list.busy',
            'value' => 'busy',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'meetings_status_list' => [
        [
            'label' => 'dropdowns.meetings_status_list.planned',
            'value' => 'planned',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.meetings_status_list.held',
            'value' => 'held',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.meetings_status_list.not_held',
            'value' => 'not_held',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.meetings_status_list.cancelled',
            'value' => 'cancelled',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
    ],
    'products_category_list' => [
        [
            'label' => 'dropdowns.product_category_list.electronics',
            'value' => 'electronics',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.product_category_list.software',
            'value' => 'software',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.product_category_list.hardware',
            'value' => 'hardware',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.product_category_list.services',
            'value' => 'services',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.product_category_list.consulting',
            'value' => 'consulting',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.product_category_list.subscriptions',
            'value' => 'subscriptions',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'dropdowns.product_category_list.licenses',
            'value' => 'licenses',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
    ],
    'products_unit_list' => [
        [
            'label' => 'dropdowns.products_unit_list.pcs',
            'value' => 'pcs',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.hr',
            'value' => 'hr',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.day',
            'value' => 'day',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.month',
            'value' => 'month',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.kg',
            'value' => 'kg',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.g',
            'value' => 'g',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.l',
            'value' => 'l',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.m',
            'value' => 'm',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.box',
            'value' => 'box',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.set',
            'value' => 'set',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.products_unit_list.flat',
            'value' => 'flat',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
    ],
    'line_items_unit_list' => [
        [
            'label' => 'dropdowns.line_items_unit_list.pcs',
            'value' => 'pcs',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.hr',
            'value' => 'hr',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.day',
            'value' => 'day',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.month',
            'value' => 'month',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.kg',
            'value' => 'kg',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.g',
            'value' => 'g',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.l',
            'value' => 'l',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.m',
            'value' => 'm',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.box',
            'value' => 'box',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.set',
            'value' => 'set',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.line_items_unit_list.flat',
            'value' => 'flat',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
    ],
    'currency_list' => [
        [
            'label' => 'dropdowns.currency_list.usd',
            'value' => 'USD',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.eur',
            'value' => 'EUR',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.gbp',
            'value' => 'GBP',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.jpy',
            'value' => 'JPY',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.cny',
            'value' => 'CNY',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.aud',
            'value' => 'AUD',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.cad',
            'value' => 'CAD',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.chf',
            'value' => 'CHF',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.inr',
            'value' => 'INR',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.currency_list.brl',
            'value' => 'BRL',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
    ],
    'module_category_list' => [
        [
            'label' => 'modules.categories.sales',
            'value' => 'sales',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'modules.categories.communication',
            'value' => 'communication',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'modules.categories.revenue',
            'value' => 'revenue',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'modules.categories.activities',
            'value' => 'activities',
            'color' => '#5b21b6',
            'bgColor' => '#ede9fe',
            'icon' => 'fa-solid fa-bolt',
        ],
        [
            'label' => 'modules.categories.support',
            'value' => 'support',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
        [
            'label' => 'modules.categories.system',
            'value' => 'system',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
    ],
    'users_status_list' => [
        [
            'label' => 'dropdowns.users_status_list.active',
            'value' => 'active',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_status_list.inactive',
            'value' => 'inactive',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_status_list.suspended',
            'value' => 'suspended',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_status_list.invited',
            'value' => 'invited',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
    ],
    'users_type_list' => [
        [
            'label' => 'dropdowns.users_type_list.admin',
            'value' => 'admin',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.executive',
            'value' => 'executive',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.sales_rep',
            'value' => 'sales_rep',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.sales_manager',
            'value' => 'sales_manager',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.support_agent',
            'value' => 'support_agent',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.marketing_user',
            'value' => 'marketing_user',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_type_list.read_only',
            'value' => 'read_only',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
    ],
    'users_title_list' => [
        [
            'label' => 'dropdowns.users_title_list.mr',
            'value' => 'mr',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.mrs',
            'value' => 'mrs',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.ms',
            'value' => 'ms',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.mx',
            'value' => 'mx',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.dr',
            'value' => 'dr',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.prof',
            'value' => 'prof',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.misc',
            'value' => 'misc',
            'color' => '#374151',
            'bgColor' => '#e5e7eb',
            'icon' => 'fa-solid fa-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.rev',
            'value' => 'rev',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.fr',
            'value' => 'fr',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.sr',
            'value' => 'sr',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.rabbi',
            'value' => 'rabbi',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.imam',
            'value' => 'imam',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.atty',
            'value' => 'atty',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.cpa',
            'value' => 'cpa',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.eng',
            'value' => 'eng',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.phd',
            'value' => 'phd',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.md',
            'value' => 'md',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.rn',
            'value' => 'rn',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.jd',
            'value' => 'jd',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.dds',
            'value' => 'dds',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.sir',
            'value' => 'sir',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.dame',
            'value' => 'dame',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.lord',
            'value' => 'lord',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.lady',
            'value' => 'lady',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.cpt',
            'value' => 'cpt',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.maj',
            'value' => 'maj',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.col',
            'value' => 'col',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.gen',
            'value' => 'gen',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.coach',
            'value' => 'coach',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.judge',
            'value' => 'judge',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.rep',
            'value' => 'rep',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.sen',
            'value' => 'sen',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.gov',
            'value' => 'gov',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.amb',
            'value' => 'amb',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.principal',
            'value' => 'principal',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.pastor',
            'value' => 'pastor',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.users_title_list.elder',
            'value' => 'elder',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
    ],
    'userinvites_status_list' => [
        [
            'label' => 'dropdowns.userinvites_status_list.pending',
            'value' => 'pending',
            'color' => '#1e40af',
            'bgColor' => '#bfdbfe',
            'icon' => 'fa-solid fa-info-circle',
        ],
        [
            'label' => 'dropdowns.userinvites_status_list.revoked',
            'value' => 'revoked',
            'color' => '#991b1b',
            'bgColor' => '#fee2e2',
            'icon' => 'fa-solid fa-times-circle',
        ],
        [
            'label' => 'dropdowns.userinvites_status_list.accepted',
            'value' => 'accepted',
            'color' => '#065f46',
            'bgColor' => '#d1fae5',
            'icon' => 'fa-solid fa-check-circle',
        ],
        [
            'label' => 'dropdowns.userinvites_status_list.expired',
            'value' => 'expired',
            'color' => '#92400e',
            'bgColor' => '#fed7aa',
            'icon' => 'fa-solid fa-exclamation-triangle',
        ],
    ],
];
