<?php

return [

    /*
    |--------------------------------------------------------------------------
    | SALES
    |--------------------------------------------------------------------------
    */

    [
        'name' => 'Leads',
        'slug' => 'leads',
        'label' => 'modules.leads.label',
        'single_label' => 'modules.leads.single_label',
        'icon' => 'fa-solid fa-user-plus',
        'color' => '#9d8f4d',
        'path' => '/leads',
        'sort_order' => 10,
        'category' => 'sales',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\LeadsModuleHandler',
        'description' => 'Prospective customers with interest.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Lead',
        'table_name' => 'leads',
        'is_custom' => 0,
    ],

    [
        'name' => 'Accounts',
        'slug' => 'accounts',
        'label' => 'modules.accounts.label',
        'single_label' => 'modules.accounts.single_label',
        'icon' => 'fa-solid fa-building',
        'color' => '#0d6efd',
        'path' => '/accounts',
        'sort_order' => 20,
        'category' => 'sales',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\AccountsModuleHandler',
        'description' => 'Company records and organizations.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Account',
        'table_name' => 'accounts',
        'is_custom' => 0,
    ],

    [
        'name' => 'Contacts',
        'slug' => 'contacts',
        'label' => 'modules.contacts.label',
        'single_label' => 'modules.contacts.single_label',
        'icon' => 'fa-solid fa-contact-book',
        'color' => '#669b6c',
        'path' => '/contacts',
        'sort_order' => 30,
        'category' => 'sales',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\ContactsModuleHandler',
        'description' => 'People assigned to accounts or leads.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Contact',
        'table_name' => 'contacts',
        'is_custom' => 0,
    ],

    [
        'name' => 'Deals',
        'slug' => 'deals',
        'label' => 'modules.deals.label',
        'single_label' => 'modules.deals.single_label',
        'icon' => 'fa-solid fa-money-bills',
        'color' => '#8080c0',
        'path' => '/deals',
        'sort_order' => 40,
        'category' => 'sales',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\DealsModuleHandler',
        'description' => 'Sales deals and revenue deals.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Deal',
        'table_name' => 'deals',
        'is_custom' => 0,
    ],

    /*
    |--------------------------------------------------------------------------
    | REVENUE
    |--------------------------------------------------------------------------
    */

    [
        'name' => 'Quotes',
        'slug' => 'quotes',
        'label' => 'modules.quotes.label',
        'single_label' => 'modules.quotes.single_label',
        'icon' => 'fa-solid fa-file-invoice-dollar',
        'color' => '#0D9488',
        'path' => '/quotes',
        'sort_order' => 50,
        'category' => 'revenue',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\QuotesModuleHandler',
        'description' => 'Sales proposals and quotes.',
        'has_line_items' => true,
        'line_item_source_module' => 'products',
        'model_class' => 'App\\Models\\Modules\\Quote',
        'table_name' => 'quotes',
        'is_custom' => 0,
        'show_in_module_manager' => true,

    ],

    [
        'name' => 'Orders',
        'slug' => 'orders',
        'label' => 'modules.orders.label',
        'single_label' => 'modules.orders.single_label',
        'icon' => 'fa-solid fa-shopping-basket',
        'color' => '#800000',
        'path' => '/orders',
        'sort_order' => 60,
        'category' => 'revenue',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\OrdersModuleHandler',
        'description' => 'Customer orders and confirmations.',
        'has_line_items' => true,
        'line_item_source_module' => 'products',
        'model_class' => 'App\\Models\\Modules\\Order',
        'table_name' => 'orders',
        'is_custom' => 0,
        'show_in_module_manager' => true,

    ],

    [
        'name' => 'Invoices',
        'slug' => 'invoices',
        'label' => 'modules.invoices.label',
        'single_label' => 'modules.invoices.single_label',
        'icon' => 'fa-solid fa-file-invoice',
        'color' => '#1E3A8A',
        'path' => '/invoices',
        'sort_order' => 70,
        'category' => 'revenue',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\InvoicesModuleHandler',
        'description' => 'Customer invoices and billing.',
        'has_line_items' => true,
        'line_item_source_module' => 'products',
        'model_class' => 'App\\Models\\Modules\\Invoice',
        'table_name' => 'invoices',
        'is_custom' => 0,
        'show_in_module_manager' => true,

    ],

    [
        'name' => 'LineItems',
        'slug' => 'line_items',
        'label' => 'modules.line_items.label',
        'single_label' => 'modules.line_items.single_label',
        'icon' => 'fa-solid fa-list-ol',
        'color' => '#05674b',
        'path' => '/line_items',
        'sort_order' => 0,
        'category' => 'revenue',
        'is_active' => false,
        'show_in_sidebar' => 0,
        'handler_class' => 'App\\Handlers\\Modules\\LineItemsModuleHandler',
        'description' => 'Customer invoices and billing Line Items ',
        'model_class' => 'App\\Models\\Modules\\LineItem',
        'table_name' => 'line_items',
        'is_custom' => 0,
        'has_owner' => false,
        'show_in_module_manager' => false,
        'is_relatable' => false,


    ],

    [
        'name' => 'Products',
        'slug' => 'products',
        'label' => 'modules.products.label',
        'single_label' => 'modules.products.single_label',
        'icon' => 'fa-solid fa-expand',
        'color' => '#b68354',
        'path' => '/products',
        'sort_order' => 80,
        'category' => 'revenue',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\ProductsModuleHandler',
        'description' => 'Product and service catalog.',
        'is_product_like' => true,
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Product',
        'table_name' => 'products',
        'is_custom' => 0,
    ],

    /*
    |--------------------------------------------------------------------------
    | SUPPORT
    |--------------------------------------------------------------------------
    */

    [
        'name' => 'Cases',
        'slug' => 'cases',
        'label' => 'modules.cases.label',
        'single_label' => 'modules.cases.single_label',
        'icon' => 'fa-solid fa-life-ring',
        'color' => '#dc3545',
        'path' => '/cases',
        'sort_order' => 90,
        'category' => 'support',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\CasesModuleHandler',
        'description' => 'Support requests, bugs, tickets.',
        'show_in_module_manager' => true,

        'model_class' => 'App\\Models\\Modules\\SupportCase',
        'table_name' => 'cases',
        'is_custom' => 0,
    ],

    /*
    |--------------------------------------------------------------------------
    | ACTIVITIES
    |--------------------------------------------------------------------------
    */

    [
        'name' => 'Tasks',
        'slug' => 'tasks',
        'label' => 'modules.tasks.label',
        'single_label' => 'modules.tasks.single_label',
        'icon' => 'fa-solid fa-list-check',
        'color' => '#5387A0',
        'path' => '/tasks',
        'sort_order' => 100,
        'category' => 'activities',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\TasksModuleHandler',
        'description' => 'To-dos and follow-ups with a due date.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Task',
        'table_name' => 'tasks',
        'is_custom' => 0,
    ],

    [
        'name' => 'Calls',
        'slug' => 'calls',
        'label' => 'modules.calls.label',
        'single_label' => 'modules.calls.single_label',
        'icon' => 'fa-solid fa-phone',
        'color' => '#DB9F5D',
        'path' => '/calls',
        'sort_order' => 110,
        'category' => 'activities',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\CallsModuleHandler',
        'description' => 'Logged and scheduled phone calls.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Call',
        'table_name' => 'calls',
        'is_custom' => 0,
    ],

    [
        'name' => 'Meetings',
        'slug' => 'meetings',
        'label' => 'modules.meetings.label',
        'single_label' => 'modules.meetings.single_label',
        'icon' => 'fa-solid fa-calendar-days',
        'color' => '#22C55E',
        'path' => '/meetings',
        'sort_order' => 120,
        'category' => 'activities',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\MeetingsModuleHandler',
        'description' => 'Scheduled meetings with a start and end time.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Meeting',
        'table_name' => 'meetings',
        'is_custom' => 0,
    ],

    [
        'name' => 'Notes',
        'slug' => 'notes',
        'label' => 'modules.notes.label',
        'single_label' => 'modules.notes.single_label',
        'icon' => 'fa-solid fa-note-sticky',
        'color' => '#65a30d',
        'path' => '/notes',
        'sort_order' => 130,
        'category' => 'activities',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\NotesModuleHandler',
        'description' => 'Freeform notes.',
        'show_in_module_manager' => true,
        'model_class' => 'App\\Models\\Modules\\Note',
        'table_name' => 'notes',
        'is_custom' => 0,
    ],

    /*
    |--------------------------------------------------------------------------
    | SYSTEM
    |--------------------------------------------------------------------------
    */

    [
        'name' => 'Settings',
        'slug' => 'settings',
        'label' => 'modules.settings.label',
        'single_label' => 'modules.settings.single_label',
        'icon' => 'fa-gears',
        'color' => '#0F172A',
        'path' => '/settings',
        'sort_order' => 999,
        'category' => 'system',
        'is_active' => false,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\SettingsModuleHandler',
        'description' => 'Application settings.',
        'has_owner' => false,
        'model_class' => 'App\\Models\\Modules\\Settings',
        'table_name' => 'settings',
        'is_custom' => 0,
        'show_in_module_manager' => false,
        'is_relatable' => false,

    ],
    [
        'name' => 'Users',
        'slug' => 'users',
        'label' => 'modules.users.label',
        'single_label' => 'modules.settings.user',
        'icon' => 'fa-solid fa-users-gear',
        'color' => '#0F172A',
        'path' => '/users',
        'sort_order' => 998,
        'category' => 'system',
        'is_active' => true,
        'show_in_sidebar' => 1,
        'handler_class' => 'App\\Handlers\\Modules\\UserModuleHandler',
        'description' => 'Users',
        'has_owner' => false,
        'model_class' => 'App\\Models\\User',
        'table_name' => 'users',
        'is_custom' => 0,
        'show_in_module_manager' => false,
        'is_relatable' => false,


    ],
    [
        'name' => 'User Invites',
        'slug' => 'userinvites',
        'label' => 'modules.userinvites.label',
        'single_label' => 'modules.userinvites.single_label',
        'icon' => 'fa-paper-plane',
        'color' => '#0F172A',
        'path' => '/users/invites',
        'sort_order' => 998,
        'category' => 'system',
        'is_active' => true,
        'is_relatable' => false,
        'show_in_sidebar' => 0,
        'handler_class' => 'App\\Handlers\\Modules\\UserInviteModuleHandler',
        'description' => 'Users Invites',
        'model_class' => 'App\\Models\\UserInvite',
        'table_name' => 'userinvites',
        'is_custom' => 0,
        'has_owner' => false,
        'show_in_module_manager' => false,

    ],
    [
        'name' => 'Pdf Template',
        'slug' => 'pdf_templates',
        'label' => 'modules.pdf_templates.label',
        'single_label' => 'modules.pdf_templates.single_label',
        'icon' => 'fa-file-pdf',
        'color' => '#3f2e03',
        'path' => '/pdf_templates',
        'sort_order' => 998,
        'category' => 'system',
        'is_active' => false,
        'is_relatable' => false,
        'show_in_sidebar' => 0,
        'handler_class' => 'App\\Handlers\\Modules\\PdfTemplateModuleHandler',
        'description' => 'Manage Pdf Template',
        'model_class' => 'App\\Models\\PdfTemplate',
        'table_name' => 'pdf_templates',
        'is_custom' => 0,
        'has_owner' => false,
        'show_in_module_manager' => false,

    ],

];
