<?php

return array(
  0 =>
  array(
    'name' => 'Inquiries',
    'slug' => 'inquiries',
    'label' => 'Inquiries',
    'single_label' => 'modules.inquiries.single_label',
    'icon' => 'fa-solid fa-mail-bulk',
    'color' => '#cceb34',
    'path' => '/inquiries',
    'sort_order' => 15,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\InquiriesModuleHandler',
    'description' => 'Manage messages from the contact form',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\ContactMessage',
    'table_name' => 'contact_messages',
    'is_custom' => 0,
  ),
  1 =>
  array(
    'name' => 'Settings',
    'slug' => 'settings',
    'label' => 'Settings',
    'single_label' => 'modules.settings.single_label',
    'icon' => 'fa-gears',
    'color' => '#7c45ba',
    'path' => '/settings',
    'sort_order' => 0,
    'is_active' => false,
    'show_in_sidebar' => 0,
    'handler_class' => 'App\\Handlers\\Modules\\SettingsModuleHandler',
    'description' => 'Settings',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Settings',
    'table_name' => 'settings',
    'is_custom' => 0,
  ),
  2 =>
  array(
    'name' => 'Accounts',
    'slug' => 'accounts',
    'label' => 'Accounts',
    'single_label' => 'modules.accounts.single_label',
    'icon' => 'fa-solid fa-building',
    'color' => '#0d6efd',
    'path' => '/accounts',
    'sort_order' => 1,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\AccountsModuleHandler',
    'description' => 'Company records and organizations.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Account',
    'table_name' => 'accounts',
    'is_custom' => 0,
  ),
  3 =>
  array(
    'name' => 'Contacts',
    'slug' => 'contacts',
    'label' => 'Contacts',
    'single_label' => 'modules.contacts.single_label',
    'icon' => 'fa-solid fa-arrows-down-to-people',
    'color' => '#669b6c',
    'path' => '/contacts',
    'sort_order' => 2,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\ContactsModuleHandler',
    'description' => 'People assigned to accounts or leads.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Contact',
    'table_name' => 'contacts',
    'is_custom' => 0,
  ),
  4 =>
  array(
    'name' => 'Leads',
    'slug' => 'leads',
    'label' => 'Leads',
    'single_label' => 'modules.leads.single_label',
    'icon' => 'fa-solid fa-user-plus',
    'color' => '#9d8f4d',
    'path' => '/leads',
    'sort_order' => 3,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\LeadsModuleHandler',
    'description' => 'Prospective customers with interest.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Lead',
    'table_name' => 'leads',
    'is_custom' => 0,
  ),
  5 =>
  array(
    'name' => 'Invoices',
    'slug' => 'invoices',
    'label' => 'Invoices',
    'single_label' => 'modules.invoices.single_label',
    'icon' => 'fa-solid fa-file-invoice',
    'color' => '#fd7e14',
    'path' => '/invoices',
    'sort_order' => 4,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\InvoicesModuleHandler',
    'description' => 'Customer invoices and billing.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Invoice',
    'table_name' => 'invoices',
    'is_custom' => 0,
  ),
  6 =>
  array(
    'name' => 'Quotes',
    'slug' => 'quotes',
    'label' => 'Quotes',
    'single_label' => 'modules.quotes.single_label',
    'icon' => 'fa-solid fa-file-invoice-dollar',
    'color' => '#ffc107',
    'path' => '/quotes',
    'sort_order' => 5,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\QuotesModuleHandler',
    'description' => 'Sales proposals and quotes.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Quote',
    'table_name' => 'quotes',
    'is_custom' => 0,
  ),
  7 =>
  array(
    'name' => 'Cases',
    'slug' => 'cases',
    'label' => 'Cases',
    'single_label' => 'modules.cases.single_label',
    'icon' => 'fa-solid fa-life-ring',
    'color' => '#dc3545',
    'path' => '/cases',
    'sort_order' => 6,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\CasesModuleHandler',
    'description' => 'Support requests, bugs, tickets.',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\SupportCase',
    'table_name' => 'cases',
    'is_custom' => 0,
  ),
  8 =>
  array(
    'name' => 'Emails',
    'slug' => 'emails',
    'label' => 'Emails',
    'single_label' => 'modules.emails.single_label',
    'icon' => 'fa-solid fa-envelope',
    'color' => '#0dcaf0',
    'path' => '/emails',
    'sort_order' => 7,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\EmailModuleHandler',
    'description' => 'Email communication module.',
    'can_view' => true,
    'can_create' => false,
    'can_edit' => false,
    'can_delete' => false,
    'model_class' => 'App\\Models\\Modules\\Email',
    'table_name' => NULL,
    'is_custom' => 0,
  ),
  9 =>
  array(
    'name' => 'Opportunties',
    'slug' => 'opportunties',
    'label' => 'Opportunties',
    'single_label' => NULL,
    'icon' => 'fa-solid fa-money-bills',
    'color' => '#8080c0',
    'path' => '/opportunties',
    'sort_order' => 8,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\OpportuntiesModuleHandler',
    'description' => '',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Opportunties',
    'table_name' => 'opportunties',
    'is_custom' => 0,
  ),
  10 =>
  array(
    'name' => 'Products',
    'slug' => 'products',
    'label' => 'Products',
    'single_label' => NULL,
    'icon' => 'fa-solid fa-expand',
    'color' => '#b68354',
    'path' => '/products',
    'sort_order' => 9,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\ProductsModuleHandler',
    'description' => '',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Products',
    'table_name' => 'products',
    'is_custom' => 0,
  ),
  11 =>
  array(
    'name' => 'Orders',
    'slug' => 'orders',
    'label' => 'Orders',
    'single_label' => NULL,
    'icon' => 'fa-solid fa-shopping-basket',
    'color' => '#800000',
    'path' => '/orders',
    'sort_order' => 10,
    'is_active' => true,
    'show_in_sidebar' => 1,
    'handler_class' => 'App\\Handlers\\Modules\\OrdersModuleHandler',
    'description' => '',
    'can_view' => true,
    'can_create' => true,
    'can_edit' => true,
    'can_delete' => true,
    'model_class' => 'App\\Models\\Modules\\Orders',
    'table_name' => 'orders',
    'is_custom' => 0,
  ),
);
